name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - name: Check flake
        run: nix flake check --no-build

      - name: Build USB image
        run: ./build.sh

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: usb-image
          path: result/
          retention-days: 7
